Fix: Fixed the broken link to contributing.md and also linked the GitHub actions badge to main branch
napptive/catalog-manager pull request #55
Opened 2022-09-08 10:39 UTC by hasnainmakada-99

### Checklist
- [ ] Code compiles correctly
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Extended the README/documentation, if necessary

#### What does this PR do?
- Made changes in the readme.md file

#### Where should the reviewer start?
- From the Readme.md file
#### What is missing?
- The link to contributing.md file
#### How should this be manually tested?
- none
#### Any background context you want to provide?
- none
#### What are the associated tickets?
- No
[PG-XX](https://napptive.atlassian.net/browse/PG-XX)

#### Screenshots (if appropriate)

#### Questions

2022-09-08 10:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/napptive/catalog-manager?pullRequest=55) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/napptive/catalog-manager?pullRequest=55) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/napptive/catalog-manager?pullRequest=55) it.</sub>

2022-11-01 08:25 UTC, hasnainmakada-99 commented
@Carmendelope @dhiguero please review this PR

2022-11-03 09:28 UTC, dhiguero requested changes
Thanks for the contribution, please review the comments.

2022-11-03 09:28 UTC, dhiguero commented on README.md
> +<a href="https://github.com/hasnainmakada-99/catalog-manager.git">![Check changes in the Main branch](https://github.com/napptive/catalog-manager/workflows/Check%20changes%20in%20the%20Main%20branch/
Please remove this change as the badge is not intended to be a link, just to show the status. Moreover, the links should point to the main repo, not to a fork.

2022-11-03 09:31 UTC, hasnainmakada-99 commented
Ok @dhiguero I'll make the changes as you requested

2022-11-03 09:54 UTC, hasnainmakada-99 commented
Hey @dhiguero I've made the changes as you requested, Please review it when you are free

2022-11-07 10:37 UTC, dhiguero approved these changes

2022-11-07 10:42 UTC, merged